### ISSUE TITLE
Please create opens:'auto' option

### ISSUE THREAD

**Issue by HTMLGuyLLC** [dangrossman/daterangepicker#1820]
I've used this plugin for a long time because it's great, but I really hate that it's not smart enough to figure out how to pad for the custom range calendars . The dropdown is slim enough that it's fine if you don't select custom, but it looks horrible when you do and it's too close to the right side (default) or left side when you have it set to open that way.

**Comment by dangrossman** [comment]
You're free to create whatever options you want!

**Comment by HTMLGuyLLC** [comment]
Bootstrap focuses on responsiveness. Your plugin is made specifically for bootstrap. It's a pity you're not more proactive about improving it's design at all screensizes. 

Not doing a pull request because I know that it needs improvement before it should be bundled into the plugin. Plus it's a bit opinionated to operate the way I want.

What this does:
When the move method is called, it'll detect if the screen is large enough to display both calendars inline. If they are not already that way, it'll calculate the amount of overflow that would exist if they were inline and subtracts that from the absolute positioning to make sure they fit. It also updates the triangle to still point at the input. If the screen is too small to fit them inline, it'll just stack them. There are only two positions now. Vertical or horizontal stacking.

The JS (replace move method and add these additional ones)
```js
calcOffset: function() {
            //default to not full width
            this.fullWidth(false);

            //if no calendars, don't worry about it.
            if( !this.container.hasClass('show-calendar') )
            {
                return 0;
            }

            var cal_left = this.container.find('.drp-calendar.left');
            var cal_right = this.container.find('.drp-calendar.right');
            var ranges = this.container.find('.ranges');

            var window_width = $(window).width();

            //calc width needed to show entire calendar in a line
            //there seems to be a padding of 2 for some reason outside the widths of the ranges and calendars
            var width = 0;
            width += ranges.outerWidth();
            width += cal_left.outerWidth();
            width += cal_right.outerWidth();

            //figure out padding
            var padding = 0;
            padding += parseInt(cal_left.css('padding-left').replace('px', ''));
            padding += parseInt(cal_left.css('padding-right').replace('px', ''));
            padding += parseInt(cal_right.css('padding-left').replace('px', ''));
            padding += parseInt(cal_right.css('padding-right').replace('px', ''));

            //if the window is not big enough to display it in a line
            if (window_width < width + padding) {
                this.fullWidth(true);
                return 0;
            }

            //how far from the side is this popup?
            var offset = this.element.offset().left;
            if (this.opens == 'right') {
                offset = this.element.offset().right;
            }

            //calculate the overflow (if any)
            var overflow = 0;
            //get the size of the popup and add the distance to the edge of the page
            overflow = width + offset + padding;
            //take the width of the popup minus the window width to get overflow
            overflow = overflow - window_width;

            //if it's not overflowing
            if (overflow <= 0)
            {
                return 0;
            }

            //if we have enough space, give 5px padding on the right
            if (window_width >= width + padding + 5) {
                overflow += 5;
            }

            return overflow;
        },

        fullWidth: function(enable){
            enable === true ? this.container.addClass('full-width') : this.container.removeClass('full-width');
        },

        move: function() {
            if( this.container.find('.pointer').length < 1 )
            {
                this.container.append('<div class="pointer"></div>');
            }

            var parentOffset = { top: 0, left: 0 },
                containerTop;
            var parentRightEdge = $(window).width();
            if (!this.parentEl.is('body')) {
                parentOffset = {
                    top: this.parentEl.offset().top - this.parentEl.scrollTop(),
                    left: this.parentEl.offset().left - this.parentEl.scrollLeft()
                };
                parentRightEdge = this.parentEl[0].clientWidth + this.parentEl.offset().left;
            }

            if (this.drops == 'up')
                containerTop = this.element.offset().top - this.container.outerHeight() - parentOffset.top;
            else
                containerTop = this.element.offset().top + this.element.outerHeight() - parentOffset.top;
            this.container[this.drops == 'up' ? 'addClass' : 'removeClass']('drop-up');

            var offset = this.calcOffset();

            if (this.opens == 'left') {
                this.container.find('.pointer').css('right', offset + 5);
                this.container.css({
                    top: containerTop,
                    right: parentRightEdge - this.element.offset().left - offset - this.element.outerWidth(),
                    left: 'auto'
                });
                if (this.container.offset().left < 0) {
                    this.container.css({
                        right: 'auto',
                        left: 9
                    });
                }
            } else if (this.opens == 'center') {
                this.container.find('.pointer').css('left', offset + 5);
                this.container.css({
                    top: containerTop,
                    left: this.element.offset().left - parentOffset.left - offset + this.element.outerWidth() / 2
                            - this.container.outerWidth() / 2,
                    right: 'auto'
                });
                if (this.container.offset().left < 0) {
                    this.container.css({
                        right: 'auto',
                        left: 9
                    });
                }
            } else {
                this.container.find('.pointer').css('left', offset + 5);
                this.container.css({
                    top: containerTop,
                    left: this.element.offset().left - offset - parentOffset.left,
                    right: 'auto'
                });
                if (this.container.offset().left + this.container.outerWidth() > $(window).width()) {
                    this.container.css({
                        left: 'auto',
                        right: 0
                    });
                }
            }
        },
```

Remove CSS:
```css
.daterangepicker:before, .daterangepicker:after {
  position: absolute;
  display: inline-block;
  border-bottom-color: rgba(0, 0, 0, 0.2);
  content: '';
}

.daterangepicker:before {
  top: -7px;
  border-right: 7px solid transparent;
  border-left: 7px solid transparent;
  border-bottom: 7px solid #ccc;
}

.daterangepicker:after {
  top: -6px;
  border-right: 6px solid transparent;
  border-bottom: 6px solid #fff;
  border-left: 6px solid transparent;
}

.daterangepicker.opensleft:before {
  right: 9px;
}

.daterangepicker.opensleft:after {
  right: 10px;
}

.daterangepicker.openscenter:before {
  left: 0;
  right: 0;
  width: 0;
  margin-left: auto;
  margin-right: auto;
}

.daterangepicker.openscenter:after {
  left: 0;
  right: 0;
  width: 0;
  margin-left: auto;
  margin-right: auto;
}

.daterangepicker.opensright:before {
  left: 9px;
}

.daterangepicker.opensright:after {
  left: 10px;
}

.daterangepicker.drop-up {
  margin-top: -7px;
}

.daterangepicker.drop-up:before {
  top: initial;
  bottom: -7px;
  border-bottom: initial;
  border-top: 7px solid #ccc;
}

.daterangepicker.drop-up:after {
  top: initial;
  bottom: -6px;
  border-bottom: initial;
  border-top: 6px solid #fff;
}

//under the media query for mobile
    .daterangepicker .ranges ul {
      width: 140px; }
    .daterangepicker.single .ranges ul {
      width: 100%; }
    
    //under the media query for .daterangepicker.ltr .drp-calendar.left {
    clear: left;
```

Add CSS:
```css
.daterangepicker.full-width
{
  width: 278px;
}
.daterangepicker.full-width .ranges,
.daterangepicker.full-width .drp-calendar
{
  width: 278px;
  width: 278px;
}

.daterangepicker .pointer
{
  position: absolute;
  display: inline-block;
  width: 5px;
  height: 5px;
  top: 0px;
  left: 5px;
}

.daterangepicker .pointer:before, .daterangepicker .pointer:after {
  position: absolute;
  display: inline-block;
  border-bottom-color: rgba(0, 0, 0, 0.2);
  content: '';
}

.daterangepicker .pointer:before {
  top: -7px;
  border-right: 7px solid transparent;
  border-left: 7px solid transparent;
  border-bottom: 7px solid #ccc;
}

.daterangepicker .pointer:after {
  top: -6px;
  border-right: 6px solid transparent;
  border-bottom: 6px solid #fff;
  border-left: 6px solid transparent;
}

.daterangepicker.opensleft .pointer:before {
  right: 9px;
}

.daterangepicker.opensleft:after {
  right: 10px;
}

.daterangepicker.openscenter .pointer:before {
  left: 0;
  right: 0;
  width: 0;
  margin-left: auto;
  margin-right: auto;
}

.daterangepicker.openscenter .pointer:after {
  left: 0;
  right: 0;
  width: 0;
  margin-left: auto;
  margin-right: auto;
}

.daterangepicker.opensright .pointer:before {
  left: 9px;
}

.daterangepicker.opensright .pointer:after {
  left: 10px;
}

.daterangepicker.drop-up {
  margin-top: -7px;
}

.daterangepicker.drop-up .pointer:before {
  top: initial;
  bottom: -7px;
  border-bottom: initial;
  border-top: 7px solid #ccc;
}

.daterangepicker.drop-up .pointer:after {
  top: initial;
  bottom: -6px;
  border-bottom: initial;
  border-top: 6px solid #fff;
}
```
